<?php

/**
 * Do not edit this file. Edit the config files in the config/ directory instead.
 * WordPress is hardcoded to look for wp-config.php in its own directory or one
 * directory up, so this loader stays in the web root.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';
